version: '3'
name: 'nestjs-skeleton'

services:
  mongodb:
    image: mongo:5.0.0
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb:/data/db
    restart: always
    environment:
      MONGO_DATABASE: nestjs
